# Generated by Django 5.0.4 on 2024-04-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='tariff',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
