# Generated by Django 5.0.4 on 2024-04-16 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0002_alter_customerbroker_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodities',
            name='descriptions',
            field=models.CharField(blank=True, choices=[('GENERALFREIGHT', 'GeneralFreight'), ('AUTOPARTS', 'AutoParts'), ('CHIP', 'Chip'), ('WATER', 'Water'), ('VEHICLE', 'Vehicle'), ('OTHER', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to='express.load'),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='pcs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='qty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='totalwt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerbroker',
            name='billing_type',
            field=models.CharField(blank=True, choices=[('NONE', 'None'), ('FACTORING_COMPANY', 'Factoring_company'), ('EMAIL', 'Email'), ('MANUAL', 'Manual')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerbroker',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerbroker',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerbroker',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customerbroker',
            name='mc_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerbroker',
            name='pod_file',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customerbroker',
            name='rate_con',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customerbroker',
            name='terms_days',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='dispatcher_tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatchertags', to='express.dispatchertags'),
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='employee_status',
            field=models.CharField(blank=True, choices=[('ACTIVE (DF)', 'ACTIVE (DF)'), ('Terminate', 'Terminate'), ('Applicant', 'Applicant')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='mc_number',
            field=models.CharField(blank=True, choices=[('ADMIN OR COMPANY MC', 'Admin or Company MC')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='position',
            field=models.CharField(blank=True, choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchertags',
            name='tag',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='assigned_dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher_drivers', to='express.dispatcher'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='assigned_trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TRailer_DRIVERS', to='express.trailer'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='assigned_truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TRUCK_DRIVERS', to='express.truck'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_license_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_license_state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Home', 'Home'), ('In-Transit', 'In-Transit'), ('Inactive', 'Inactive'), ('Shop', 'Shop'), ('Rest', 'Rest'), ('Dispatched', 'Dispatched')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivertags', to='express.drivertags'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('ACTIVE (DF)', 'ACTIVE (DF)'), ('Terminate', 'Terminate'), ('Applicant', 'Applicant')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='payd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='permile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='tariff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='team_driver',
            field=models.CharField(blank=True, choices=[('DRIVER_2', 'Driver_2'), ('ASSIGNED_DISPATCHER', 'Assigned_dispatcher'), ('PERCENT_SALARY', 'Percent_salary')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drivertags',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(blank=True, choices=[('ACTIVE (DF)', 'ACTIVE (DF)'), ('Terminate', 'Terminate'), ('Applicant', 'Applicant')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeetags', to='express.employeetags'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('ACCOUNTING', 'Accounting'), ('FLEET MANAGMENT', 'Fleet Managment'), ('SAFETY', 'Safety'), ('HR', 'hr'), ('UPDATER', 'Updater'), ('ELD TEAM', 'ELD team'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeetags',
            name='tag',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='loadtags',
            name='tag',
            field=models.CharField(blank=True, choices=[('HAZ', 'Haz'), ('DEDICATED LANE', 'Dedicated Lane'), ('HOT LOAD', 'Hot Load'), ('ISSUE', 'Issue')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otherpay',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='otherpay',
            name='load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otherpay', to='express.load'),
        ),
        migrations.AlterField(
            model_name='otherpay',
            name='pay',
            field=models.CharField(blank=True, choices=[('ACCESSORIALS', 'Accessorials'), ('PAYAMOUNT', 'PayAmount'), ('OTHERCHARGES', 'OtherCharges'), ('FUEL', 'Fuel'), ('BROKERFEE', 'BrokerFee')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otherpay',
            name='type',
            field=models.CharField(blank=True, choices=[('DETENTION', 'Detention'), ('EMPTYMILES', 'EmptyMiles'), ('EXTRAMILES', 'ExtraMiles'), ('FLAT', 'Flat'), ('LAYOVER', 'Layover'), ('LINEHOUL', 'Linehoul'), ('FUELSURCHARGE', 'FuelSurcharge'), ('LUMPER', 'Lumper'), ('EXTRASTOP', 'ExtraStop'), ('TONU', 'TONU'), ('BONUS', 'Bonus'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='appointmentdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='express.load'),
        ),
        migrations.AlterField(
            model_name='stops',
            name='reference_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_name',
            field=models.CharField(blank=True, choices=[('PICKUP', 'Pickup'), ('DELIVERY', 'Delivery')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='driver',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='make',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='mc_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='ownership',
            field=models.CharField(blank=True, choices=[('COMPANY', 'Company'), ('OWNER_OPERATOR', 'Owner-operator'), ('LEASE', 'Lease'), ('RENTAL', 'Rental')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trailertags', to='express.trailertags'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='type',
            field=models.CharField(blank=True, choices=[('REEFER', 'Reefer'), ('DRYVAN', 'Dryvan'), ('STEPDECK', 'Stepdeck'), ('LOWBOY', 'Lowboy'), ('CARHAUL', 'Carhaul'), ('FLATBED', 'Flatbed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='unit_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='vin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trailertags',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='assignment_status',
            field=models.CharField(blank=True, choices=[('AVAILABLE', 'Company'), ('INACTIVE', 'Inactive')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='driver',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='mc_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('COMPANY', 'Company'), ('OWNER_OPERATOR', 'Owner-operator'), ('LEASE', 'Lease'), ('RENTAL', 'Rental'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='plate_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trucktags', to='express.trucktags'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='unit_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='vin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trucktags',
            name='tag',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
