# Generated by Django 5.0.4 on 2024-04-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0003_alter_driver_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='per_mile',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
