# Generated by Django 5.0.4 on 2024-04-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0004_alter_load_driver_pay_alter_load_load_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='total_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
