# Generated by Django 5.0.4 on 2024-04-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0004_alter_load_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_type',
            field=models.CharField(blank=True, choices=[('COMPANY_DRIVER', 'Company_driver'), ('OWNER_OPERATOR', 'Owner_operator'), ('LEASE', 'Lease'), ('RENTAL', 'Rental')], max_length=50, null=True),
        ),
    ]
