# Generated by Django 5.0.4 on 2024-04-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0004_alter_load_per_mile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='per_mile',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
