# Generated by Django 5.0.4 on 2024-04-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0005_alter_load_total_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='total_pay',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
