# Generated by Django 5.0.4 on 2024-04-18 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0005_alter_driver_driver_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('load_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_id_chat', to='express.load')),
            ],
        ),
    ]
