# Generated by Django 5.0.4 on 2024-04-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0006_alter_load_total_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='driver_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='load_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='total_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='otherpay',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
