# Generated by Django 5.0.4 on 2024-04-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0006_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbroker',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
