# Generated by Django 5.0.4 on 2024-04-15 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0006_alter_load_per_mile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher', to='express.dispatcher'),
        ),
        migrations.AlterField(
            model_name='load',
            name='customer_broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_broker', to='express.customerbroker'),
        ),
        migrations.AlterField(
            model_name='load',
            name='dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='express.dispatcher'),
        ),
        migrations.AlterField(
            model_name='load',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='express.driver'),
        ),
        migrations.AlterField(
            model_name='load',
            name='rate_con',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='load',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loadtags', to='express.loadtags'),
        ),
        migrations.AlterField(
            model_name='load',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='express.truck'),
        ),
    ]
