# Generated by Django 5.0.4 on 2024-04-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0007_customerbroker_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='bills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='instructions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='reference_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='created_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='load_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='appointmentdate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
