# Generated by Django 5.0.4 on 2024-04-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0008_load_bills_load_company_name_load_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='ai',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
